const { Schema, Types, model } = require('mongoose');
const vacationCard = new Schema({
    _id:Types.ObjectId,
    title:{
        type:String
    },
    caption:{
        type:String
    },
    imageSrc:{
        type:String
    },
    fullDescription:{type:String
    },
    stays:{
        type:Boolean,
        require,
        select: false,
    },
    label:{type:String,
    require
    },
    name_place:{type:String,
    require
    },
    discount:{type:String,
        require
    },
    check_in:{type:Date,
    require
    },
    check_out:{type:Date,
        require
    },
    Guests:{type:Number,
    require
    },
    Flight_Details:{type:String,
        require
    },
    Airport_shuttle_included:{
        type:Boolean,
        require
    },
    Breakfast_included:{
        type:Boolean,
        require
    },
    Lunch_included:{
        type:Boolean,
        require
    },
    Dinner_included:{
        type:Boolean,
        require
    },
    Parking:{
        type:Boolean,
        require
    },
    Pool:{
        type:Boolean,
        require
    },
    price:{type:String,
    require},
    Price_per_night:{type:Number,
        require
    },
    Guest_rating:{type:Number,
        require
    },
    Star_rating:{type:Number,
        require
    },
    Pet_friendly:{
        type:Boolean,
        require
    },
    Hot_tub:{
        type:Boolean,
        require
    },
    Kitchen:{
        type:Boolean,
        require
    },
    Wifi:{
        type:Boolean,
        require
    },
    Spa:{
        type:Boolean,
        require
    },
    Cribs:{
        type:Boolean,
        require
    },
    Ocean_view:{
        type:Boolean,
        require
    },
    Restaurant:{
        type:Boolean,
        require
    },
    Electric_car_charging_station:{
        type:Boolean,
        require
    },
    Air_conditioned:{
        type:Boolean,
        require
    },
    Gym:{
        type:Boolean,
        require
    },
    Water_park:{
        type:Boolean,
        require
    },
    In_room_accessibility:{
        type:Boolean,
        require
    },
    Accessible_bathroom:{
        type:Boolean,
        require
    },
    Elevator:{
        type:Boolean,
        require
    },
    Fully_refundable:{
        type:Boolean,
        require
    },
    ReserveNow_payLater:{
        type:Boolean,
        require
    },
    PropertyType:{type:String,
        require
    }
})
module.exports = model('Card', vacationCard)

